# Generated by Django 2.1.7 on 2019-03-29 00:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lender_app', '0002_auto_20190327_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 29, 0, 0, 50, 832629, tzinfo=utc)),
        ),
    ]
